# -*- coding: utf-8 -*-
"""bmi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GNpS-73QaWu89L4BDpeM4hKM2J_zbEHC
"""

# function declaration
# keyword: def
def function_name(greetings, name):
  return '{}, {}'.format(greetings,  name)
print(function_name("Hi", "Belise"))
  #statement 

# checked: wonderful

# example
def show():
  # statement
  print("this is a function")

"""
to ge the output from the above function, you have to make what we call function call. assume you have the lamp off, to turn the light on, you have to hit 
the button. so hitting the button is analogous to the function call. calling the function is just to take the write the function_name and open and close 
brackets
"""
# call the show function
show()

# to do 
"""write a function to print out your full names"""
# write code below this line
def my_names(fname = "Gahongayire", lname = "Belise"):
  print( fname + " " + lname)
my_names("Gahongayire", "Belise")

# checked: nice

"""suppose the lump has more than one type of output light color example: yellow, red & default white color. then here you need pass the name of the 
color you want to see the lump light up"""
def lump(color = "white"):
  # the color is defaultly set to be white
  print("current lump color is ", color)

# turn on the lump. i mean call the function
lump()

# change the lump color to be re
# to change the color, this action takes place when you are calling your function
lump(color = "red")

# to do
# make a function that adds two variable x and y. set default value for x to be 10 and 4 for y and later change those values as i did in the above example
# write codes here
def sum(x=10, y=4):
  print("The sum is", x+y)
sum()

# N.B> TRY AS MUCH AS YOU CAN TO DO THE PRACTICE

# congratulations for this progress! you did it very well

"""ASSIGNMENT 2: #CREATE A FUNCTION THAT ACCEPT A USER'S NAME, AGE, HEIGHT & WEIGHT"""

# compute body mass index (BMI)
# BMI = weight / (square of height)
# output example: Irene with age 30 has BMI of 22.5
# try to accept atleast 5 user minimum.
# if the BMI > 25 say that this guy is obese
# if BMI < 25 and not less than 18 say that this guy is normal & healthy
# if BMI < 18 say this guy is underweight

# name:
# weight:
# height:
# bmi = weight / (height **2)

# if bmi < 25:
# return name is obess
# elif: bmi < 25 and bmi > 18:
# return name is normal
# else:
# return name is underweight

def bmi(name, weight, height):
  bmi = round(weight/ (height **2), 2)
  if bmi > 25:
    return name + ' is ' + 'obess ' + f'with bmi: {bmi}'
    print(' ')
  elif bmi < 25 and bmi > 18 :
    return name + ' is ' +  'normal ' + f'with bmi: {bmi}' 
  else:
   return  name + ' is ' + 'underweight ' + f'with bmi: {bmi}'

var = bmi ('jean', 50,1)

for member in range (3):
  name = input('name:')
  weight = float(input('weight'))
  height = float(input('height'))
  check_up = bmi(name,weight,height)
  print(check_up)
  print(' '*100)

while True:
  name = input('name:')
  weight = float(input('weight'))
  height = float(input('height'))
  check_up = bmi(name,weight,height)
  print(check_up)
  print(' '*100)

  choice = input('continue: Yes or No ')
  if choice in  'yes':
    pass
  else:
    break

import random

number = "+25078"
formed_number = []

for i in range(200):
  for num in  range(7):
    choosen = random.randrange(0,9)
    number += str(choosen)
  if number not in formed_number:
    formed_number.append(number)
    number = "+25078"
  else:
    number = "+25078"
print(formed_number)

